// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Calculator/protos/calculator.proto
// Original file comments:
// Copyright 2017, Google Inc.
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are
// met:
//
//     * Redistributions of source code must retain the above copyright
// notice, this list of conditions and the following disclaimer.
//     * Redistributions in binary form must reproduce the above
// copyright notice, this list of conditions and the following disclaimer
// in the documentation and/or other materials provided with the
// distribution.
//     * Neither the name of Google Inc. nor the names of its
// contributors may be used to endorse or promote products derived from
// this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using Grpc.Core;

namespace GrpcCalculator {
  public static class CalculatorService
  {
    static readonly string __ServiceName = "CalculatorService";

    static readonly Marshaller<global::GrpcCalculator.TrigRequest> __Marshaller_TrigRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GrpcCalculator.TrigRequest.Parser.ParseFrom);
    static readonly Marshaller<global::GrpcCalculator.MathResponse> __Marshaller_MathResponse = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GrpcCalculator.MathResponse.Parser.ParseFrom);

    static readonly Method<global::GrpcCalculator.TrigRequest, global::GrpcCalculator.MathResponse> __Method_sine = new Method<global::GrpcCalculator.TrigRequest, global::GrpcCalculator.MathResponse>(
        MethodType.Unary,
        __ServiceName,
        "sine",
        __Marshaller_TrigRequest,
        __Marshaller_MathResponse);

    static readonly Method<global::GrpcCalculator.TrigRequest, global::GrpcCalculator.MathResponse> __Method_cosine = new Method<global::GrpcCalculator.TrigRequest, global::GrpcCalculator.MathResponse>(
        MethodType.Unary,
        __ServiceName,
        "cosine",
        __Marshaller_TrigRequest,
        __Marshaller_MathResponse);

    static readonly Method<global::GrpcCalculator.TrigRequest, global::GrpcCalculator.MathResponse> __Method_tan = new Method<global::GrpcCalculator.TrigRequest, global::GrpcCalculator.MathResponse>(
        MethodType.Unary,
        __ServiceName,
        "tan",
        __Marshaller_TrigRequest,
        __Marshaller_MathResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::GrpcCalculator.CalculatorReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of CalculatorService</summary>
    public abstract class CalculatorServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::GrpcCalculator.MathResponse> sine(global::GrpcCalculator.TrigRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::GrpcCalculator.MathResponse> cosine(global::GrpcCalculator.TrigRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::GrpcCalculator.MathResponse> tan(global::GrpcCalculator.TrigRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for CalculatorService</summary>
    public class CalculatorServiceClient : ClientBase<CalculatorServiceClient>
    {
      /// <summary>Creates a new client for CalculatorService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public CalculatorServiceClient(Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for CalculatorService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public CalculatorServiceClient(CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected CalculatorServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected CalculatorServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::GrpcCalculator.MathResponse sine(global::GrpcCalculator.TrigRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return sine(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::GrpcCalculator.MathResponse sine(global::GrpcCalculator.TrigRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_sine, null, options, request);
      }
      public virtual AsyncUnaryCall<global::GrpcCalculator.MathResponse> sineAsync(global::GrpcCalculator.TrigRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return sineAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncUnaryCall<global::GrpcCalculator.MathResponse> sineAsync(global::GrpcCalculator.TrigRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_sine, null, options, request);
      }
      public virtual global::GrpcCalculator.MathResponse cosine(global::GrpcCalculator.TrigRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return cosine(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::GrpcCalculator.MathResponse cosine(global::GrpcCalculator.TrigRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_cosine, null, options, request);
      }
      public virtual AsyncUnaryCall<global::GrpcCalculator.MathResponse> cosineAsync(global::GrpcCalculator.TrigRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return cosineAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncUnaryCall<global::GrpcCalculator.MathResponse> cosineAsync(global::GrpcCalculator.TrigRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_cosine, null, options, request);
      }
      public virtual global::GrpcCalculator.MathResponse tan(global::GrpcCalculator.TrigRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return tan(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::GrpcCalculator.MathResponse tan(global::GrpcCalculator.TrigRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_tan, null, options, request);
      }
      public virtual AsyncUnaryCall<global::GrpcCalculator.MathResponse> tanAsync(global::GrpcCalculator.TrigRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return tanAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncUnaryCall<global::GrpcCalculator.MathResponse> tanAsync(global::GrpcCalculator.TrigRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_tan, null, options, request);
      }
      protected override CalculatorServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new CalculatorServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    public static ServerServiceDefinition BindService(CalculatorServiceBase serviceImpl)
    {
      return ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_sine, serviceImpl.sine)
          .AddMethod(__Method_cosine, serviceImpl.cosine)
          .AddMethod(__Method_tan, serviceImpl.tan).Build();
    }

  }
}
#endregion
